name: UI Automation Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Running Automation Tests using Maven
        run: mvn clean test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: test-automation-logs
          path: logs/

      - name: Upload Screenshots as Artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: screenshots
          path: screenshots/

      - name: Archive Extent Reports
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: extent-reports
          path: reports/

      - name: Test Execution Status
        run: echo "Tests completed"

      - name: Copy Report to gh-pages Folder
        if: always()
        run: |
          mkdir -p public/extent-reports
          cp -R reports/ public/extent-reports/
          cp -R screenshots/ public/extent-reports/screenshots/
          ls -l 

      - name: Deploy 🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          folder: public/extent-reports/
          token: ${{ secrets.REPOPAT }}
          clean: true
