name: UI Automation Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Run Tests
      run: mvn clean test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-automation-logs
        path: logs/

    - name: Archive Extent Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: extent-reports
        path: reports/
    
    - name: Test Execution Status
      run: echo "Tests completed"
